export const GET_STATUS_HISTORY_REQUEST = 'GET_STATUS_HISTORY_REQUEST';
export const GET_STATUS_HISTORY_SUCCESS = 'GET_STATUS_HISTORY_SUCCESS';
export const GET_STATUS_HISTORY_FAILURE = 'GET_STATUS_HISTORY_FAILURE';
