export const GET_CURRENT_STATUS_REQUEST = 'GET_CURRENT_STATUS_REQUEST';
export const GET_CURRENT_STATUS_FAILURE = 'GET_CURRENT_STATUS_FAILURE';
export const GET_CURRENT_STATUS_SUCCESS = 'GET_CURRENT_STATUS_SUCCESS';


export const SET_CURRENT_STATUS_REQUEST = 'SET_CURRENT_STATUS_REQUEST';
export const SET_CURRENT_STATUS_FAILURE = 'SET_CURRENT_STATUS_FAILURE';
export const SET_CURRENT_STATUS_SUCCESS = 'SET_CURRENT_STATUS_SUCCESS';
