export const GET_USER_PROJECTS_REQUEST = 'GET_USER_PROJECTS_REQUEST';
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS';
export const GET_USER_PROJECTS_FAILURE = 'GET_USER_PROJECTS_FAILURE';

export const ADD_USER_PROJECT_SUCCESS = 'ADD_USER_PROJECT_SUCCESS';
export const DELETE_USER_PROJECT_SUCCESS = 'DELETE_USER_PROJECT_SUCCESS';
export const EDIT_USER_PROJECT_SUCCESS = 'EDIT_USER_PROJECT_SUCCESS';
