export const GET_USER_PROJECTS_REQUEST = 'GET_USER_PROJECTS_REQUEST';
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS';
export const GET_USER_PROJECTS_FAILURE = 'GET_USER_PROJECTS_FAILURE';
