export const GET_REMINDERS_REQUEST = 'GET_REMINDERS_REQUEST';
export const GET_REMINDERS_SUCCESS = 'GET_REMINDERS_SUCCESS';
export const GET_REMINDERS_FAILURE = 'GET_REMINDERS_FAILURE';

export const DELETE_REMINDER_REQUEST = 'DELETE_REMINDER_REQUEST';
export const DELETE_REMINDER_SUCCESS = 'DELETE_REMINDER_SUCCESS';
export const DELETE_REMINDER_FAILURE = 'DELETE_REMINDER_FAILURE';

export const EDIT_REMINDER_REQUEST = 'EDIT_REMINDER_REQUEST';
export const EDIT_REMINDER_SUCCESS = 'EDIT_REMINDER_SUCCESS';
export const EDIT_REMINDER_FAILURE = 'EDIT_REMINDER_FAILURE';

export const CREATE_REMINDER_REQUEST = 'CREATE_REMINDER_REQUEST';
export const CREATE_REMINDER_SUCCESS = 'CREATE_REMINDER_SUCCESS';
export const CREATE_REMINDER_FAILURE = 'CREATE_REMINDER_FAILURE';