export const LOGIN_AUTHORIZATION_SUCCESS = 'LOGIN_AUTHORIZATION_SUCCESS';
export const LOGIN_AUTHORIZATION_REQUEST = 'LOGIN_AUTHORIZATION_REQUEST';
export const LOGIN_AUTHORIZATION_FAILURE = 'LOGIN_AUTHORIZATION_FAILURE';